### PR TITLE
Jvehent rework tomato42 curves tolerance 5

### PR DESCRIPTION
**Pull request by jvehent**
Implements #46 with a number of changes.

### CODE REVIEW

**Comment by tomato42** [comment]
When I run it against a `-named_curve auto` openssl, it reports support only for sect571r1, similarly, when I scan login.live.com I'm getting just secp521r1

**Comment by tomato42** [comment]
the new JSON format doesn't put the `curves_fallback` inside the `ciphersuite` results

**Comment by jvehent** [comment]
Right, `curves_fallback` is tested as a global option, not for each ciphersuite. It's similar to how server side ordering is represented.

**Comment by jvehent** [comment]
@tomato42: without --curves, cipherscan will only display IANA name of the default curve in the curves column. I left --curves turned off by default because I think it has little value right now, considering the minimal percentage of servers that support more than one curve, but that could be changed in the future.

**Comment by jvehent** [comment]
and by `little value`, I mean that the feature is great and very useful, but 99.9% of results would probably return a single curve, so enabling it by default for everyone doesn't have a lot of benefits

**Comment by tomato42** [comment]
yeah, I was just confused by the test checking if openssl in use supports the option

**Comment by tomato42** [comment]
ok then, I don't see anything else problematic
r+

BTW, the raw data from scans is finally available: https://scans.io/study/fedora-cipherscan

**Comment by jvehent** [comment]
Nice! Thanks for the review and the patches!
Hopefully, this should be stable enough. We can always fix bugs as they should up.

**Comment by tomato42** [comment]
OK, thanks for the merge.

The question is, how do you want the tests for signature algorithms for PFS ciphers (DHE, ECDHE)? Also tested on a per-cipher basis or should I leave them as-is, with just one test for the whole server?

**Pull request merged**
