### PR TITLE
Result parser update

### PR DESCRIPTION
**Pull request by tomato42**
world moves on, update the results parser to accommodate it

### CODE REVIEW

**Comment by jvehent** [comment]
Not that I don't enjoy these patches (I think they are great), but wouldn't you prefer to port those to the [TLS Observatory](https://github.com/mozilla/tls-observatory) instead so you can benefit from the scanner infrastructure and the database?

**Comment by tomato42** [comment]
the whole point for me for the `cipherscan` is to be standalone and easy to run

I already told you what's my position on [go](https://github.com/ksimka/go-is-not-good), and it haven't changed

I will be focusing on intolerancies now (with TLSv1.3 just around the corner), so results parser won't see much updates in near future anyway

**Comment by jvehent** [comment]
Eh, didn't mean that as a language war, you're welcome to use whatever language you like :)
I just proposed that you benefit from the hosted scanner and the database that keeps all records to run differential queries between months.

**Comment by tomato42** [comment]
ok, I may take a look at it as a user, though I'm not exactly eager to install go on my machine :)

thanks for the reviews!

**Pull request merged**
