### PR TITLE
TLS intolerancies

### PR DESCRIPTION
**Pull request by tomato42**
As some servers are TLS intolerant, it would be nice to be able to detect at least intolerancies for TLS 1.2 Client Hello.

### CODE REVIEW

**Comment by tomato42** [comment]
@jvehent this is the first of the big feature patches, so I'll wait for this one to be reviewed before submitting others. I have rebased them on current master so it should be easy to provide them in timely manner now (sorry for the delay since the curves patches were merged!).

**Comment by jvehent** [comment]
Thanks! I'll take a look soon. I'm traveling across Europe at the moment, so it may be a couple weeks before I can review it.

**Comment by tomato42** [comment]
ping?

**Comment by jvehent** [comment]
Still traveling... (at dfir summit right now). I just started going through my backlog of reviews. This one is up next!

**Comment by jvehent** [comment]
@tomato42: I think this is good to merge but needs a rebase. Could you do it and ping me then?

**Comment by tomato42** [comment]
@jvehent: rebased

**Comment by PeterMosmans** [comment]
That turnaround time...  :zap:
beyond magic :smile:

**Comment by jvehent** [comment]
lucky luke

**Comment by tomato42** [comment]
:smile:

**Pull request merged**
