### PR TITLE
Tests for TLS1.2 PFS key exchanges

### PR DESCRIPTION
**Pull request by tomato42**
Add tests for supported signature algorithms for TLS1.2 key exchanges, check if ordering used is forced by server, or if the server prefers algorithms preferred by client.

### CODE REVIEW

**Comment by tomato42** [comment]
@jvehent: when can I expect review?

**Comment by jvehent** [comment]
Doh! Forgot about it! I'm moving it back on the todo list!

**Comment by jvehent** [comment]
I started reviewing today, but this is a complex addition that needs more time than I can give it right now. It'll have to wait a little longer :/

**Comment by tomato42** [comment]
rebased on top of master. With the exception of adding colour output and reusing function instead of defining a new one it is unchanged from the one proposed on 16th of July (b9d1e08)

**Comment by jvehent** [comment]
I would like to refine it a bit later, but for now it should be merged and not sit stale any longer. Since sigalg scanning is off by default, it really has little impact on normal use, and I like what it does a lot!

Thanks @tomato42 :+1:

**Comment by tomato42** [comment]
thanks!

if you have any ideas how to make those tests better you know where to find me :wink:

**Pull request merged**
