### PR TITLE
Enable Server Name Indication by default

### PR DESCRIPTION
**Pull request by jvehent**
@tomato42: r?

### CODE REVIEW

**Comment by floatingatoll** [comment]
IP addresses are permitted in SSL certificates (ipAddress: type, rather than DNS: type), so you might consider either emitting a warning instead of silently disabling SNI in that case.

**Comment by floatingatoll** [comment]
Is using SNI inappropriate if the target is an IP address? It says to the server "we want the SSL certificate for IP x", which will fallthrough to the default unless they happen to have one, and then you don't have to try and waste CPU checking whether a hostname is an ipv4/ipv6 address or is a valid local hostname or etc.

**Comment by jvehent** [comment]
@tomato42: you regex fails to catch ipv6. mine only looks for a TLD, not a hostname, which really should be `[a-z]` but I agree we could check for `[a-zA-Z]`

@floatingatoll: SNI itself cannot be an IP address, so if the target is an IP address, we can't just insert the target into the SNI field.

**Comment by floatingatoll** [comment]
If you want an IP address testing regex, http://unix.stackexchange.com/a/19619 seems fully complete.

**Comment by jvehent** [comment]
Added a warning, that should do it.

**Pull request merged**
