### PR TITLE
Update analyze.py

### PR DESCRIPTION
**Pull request by Emantor**
Per https://mozilla.github.io/server-side-tls/ssl-config-generator/
The intermediate config supports 'ECDHE-RSA-DES-CBC3-SHA', add it to analyze.py.

### CODE REVIEW

**Comment by Emantor** [comment]
Fix #85

**Comment by jvehent** [comment]
Thanks for the patch. However, `ECDHE-RSA-DES-CBC3-SHA` needs to be placed right after `DHE-RSA-AES256-SHA`, not after `AES256-SHA`, so PFS is always first. Could you resubmit using the exact ciphersuite from https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28default.29 ?

**Comment by Emantor** [comment]
It is, `DHE-RSA-` is on the upper line.

**Comment by Emantor** [comment]
I added `ECDHE-ECDSA-DES-CBC3-SHA` as well.

**Comment by jvehent** [comment]
Ha, my bad, I misread the commit.
This looks good. Merging, and thanks for the patch :)

**Pull request merged**
