### PR TITLE
A few fixes to the terminal output

### PR DESCRIPTION
**Pull request by jvehent**

### CODE REVIEW

**Comment by jvehent** [comment]
@tomato42: r?

**Comment by tomato42** [comment]
In general I think that KO and OK are too similar, and something like NAK or ERR would be better

and while we're at the topic of making output more clear... how about colour? the basic ANSI escape sequences are supported everywhere bash runs

**Comment by jvehent** [comment]
I though about colors. It could be a nice addition, assuming it doesn't break copy/paste as I've seen it do (forgot why exactly, maybe depends on the terminal?).

**Comment by tomato42** [comment]
I never seen colour breaking copy/paste... standard config of `less` sure, but then we certainly don't want to print so much info by default as to make use of less needed...

**Comment by jvehent** [comment]
I think that's all of it. the colored output looks quite nice.

screnshot

**Comment by tomato42** [comment]
@jvehent: In general, if you could --rebase and squash commits when you fix them up, that would make reviewing much easier

**Pull request merged**
